[google_sheets]
spreadsheet_id = "GANTI_ID_SPREADSHEET_ANDA"
sheet_name     = "Data Peserta"

[imgbb]
api_key = "GANTI_DENGAN_API_KEY_IMGBB_ANDA"

[gcp_service_account]
type                        = "service_account"
project_id                  = "form-absensi"
private_key_id              = "fa8cb73dab49452147ebe4d9318a2b5375d45017"
private_key                 = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDCnqxbln/E0I0j
kl0Oj4xUckJh3tceRGIa4JFnasAJe33Zs5Y3TC9K71aUwGKx98ONpIEN9DEb+azX
cfEpNwxwiWiHix7D9w6nh2qSQTo10lrnVOKAV/c3B5nWFI6/FYxQsX42kL/Lp1f0
NAdNph23tw9fzqGpxoLfhOwzAv8L2QOay0WorEUWF01hBsSuagiV/BqJOws57w9d
4fktnUBy/RjxlhrPHjKGMLZFnE3kDNL0IYEf2UUzElo0y8xvzq59vkkXeYXfEKa2
Nv8sjgipXrCQ4/eG2MD6qs+LJWTil8YygQJNizOvIdllW8twG6Sry/U0nuqEBWaT
3LVd77FFAgMBAAECggEANE9PxmJCP1VKykfZyUMeFciMPSAXM+RvdgfsLR7NNP9D
SVNyybQpdfu0itDW9jzBC/4uTeDXnkxSf6n5hvlr14enV981yrhJ8Q99vofXrIW4
tzriklqScPETES5/W67gAwRiByqK0qNNCa8+U0mV7T4/3KF+ZFKd9JQWpHNmt/kJ
aIInE5LthXr0g1Dk1LrKkmWOMM2izeXJpAXyaokU/3VmWcCv65jtnSE5xoqmpge8
sFugDafFjsDcNjBn/6ozB0URbhoxS0dWgl/871YN/JbFrX4weHS/Za/fHGGVjG95
hch9LnKKBF6qwZMG3xKr4/Eyvy16y0H4lq4IIDyCtQKBgQDmhegGmkjsRZLYgZJq
QNgTqqKXW5xm09uw/shYp+4WclGfPlh0FUHqaNbpgJYSj+AERT4jOD+3M9ATq0Yw
9QpDk6HzIkoul46NqIpH08uKC/27vRhFIlRm406YcMQllxfrd7Y70Sidr1vpAxbv
rDxWP5il/43a9LSjl4j8wrrSHwKBgQDYIPiWPnpZ9OpzH/1tT9sCk+NHAY7V/goS
/b/DP81P+/SQoZFstLQUhXuIUn9ga/03NB9tDwBjN/myqZoYoybaxMnSRWm26iN5
5DRgvUy2wtzvIGMLdNlX62TOpnQ6e/PMwncjVq0Efs+0EXBvyHE7wNb4hs/WN1Xw
CxGviKN4GwKBgHoKmnQkakbr7npA3srx2XNP+xQ2o+6sarqhqF+HSD0J+LxdvWZ3
epYnOuAT+1+IXAjmv6bVuKW9AIPpQRfaIrz0A+E8XhmckxPcDplIP5GuF3609Yxk
SFrQLGP4D1/3ReqbThcM/Hu+wuHxiMsKXEctFBuN2AP7WUbiituGHHHxAoGAewgR
2p1IUwsbp1uPjXmG5+m92H7ni6OoonT2g7Q/MQfxiZ+fxCz90izGTK0Bu6bdp14x
gYinpNOJfg4UHXBKvwCFDwDak/inJ00kD+nS0LsOv8VE/JGQ4/6pDQYuZdiHyYjt
/xzpMwTpQc0nn0qQQv6coS9FAuHPNu1mLPFwdP8CgYEAiJ0UDZH87V8r+lHkxHVW
HMLeJ5NMjhttb1bDa9rSamchO/gKFJh9+NW9V4KUsKApvAFEFBjfF8LZkOXA5a0m
9Bi9YHNZFyRF22r2uzMQwjwKbuiCqqcyWnYZJu2pzAA36hjrDiXjREhTmKXPyWvF
VSOnfMKsg+qtJCzdoC67pH8=
-----END PRIVATE KEY-----
"""
client_email                = "streamlit-form@form-absensi.iam.gserviceaccount.com"
client_id                   = "111507841892509189681"
auth_uri                    = "https://accounts.google.com/o/oauth2/auth"
token_uri                   = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url        = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-form%40form-absensi.iam.gserviceaccount.com"
universe_domain             = "googleapis.com"
